### ISSUE TITLE
WP Mail SMTP settings disappear on Multisite with ANM

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/admin-notices-manager#63]
1) Install WP Mail SMTP on the network
2) Install ANM
3) The settings do not load up:

![image](https://user-images.githubusercontent.com/3965050/153627968-e3b20b2d-44d2-4fb0-8287-dae87a459232.png)

4) Without ANM all works well:

![image](https://user-images.githubusercontent.com/3965050/153628018-e607f596-0006-4f16-9129-3bd7b7bf075c.png)

Let's fix this and also test it on the single site once at it.

**Comment by capuderg** [comment]
Hi @martinkrcho,

I'm the lead developer for WP Mail SMTP plugin.

Since your plugin is managing admin notices and we are removing all other ones on our pages, I would recommend going with option 2, because there won't be any notices to manage, except our own :)

You could of course hook into our code and disable the `hide_unrelated_notices`, like so:

```
add_action( 'network_plugin_loaded', function () {

	if ( ! function_exists( 'wp_mail_smtp' ) ) {
		return;
	}

	remove_action( 'admin_print_scripts', [ wp_mail_smtp()->get_admin(), 'hide_unrelated_notices' ] );
} );
```

Have a nice day!

**Comment by martinkrcho** [comment]
> You could of course hook into our code and disable the `hide_unrelated_notices`

Thanks for the advice, @capuderg . We're going to add this to our plugin.

**Comment by capuderg** [comment]
As I said, we would prefer option 2, because this change will display all admin notices on our plugin pages (because you are removing the hook where we originally remove all other admin notices). This would actually make our user's experience worse because they would see all the admin notices on our admin pages by default if your plugin would be active.

With the code above I just wanted to provide a way on how to hook in our code, if you'll ever need it in the future.

**Comment by martinkrcho** [comment]
I see. No problem.

How about my suggestion number 1?
> Get in touch with plugin authors and ask them to clear `network_admin_notices` hook along with the other three.

Is there any reason why you're not removing actions hooked into `network_admin_notices`?

**Comment by capuderg** [comment]
Oh, I misunderstood you first point. You are suggesting that we also clear `network_admin_notices`, like so: 

`$this->remove_unrelated_actions( 'network_admin_notices' );`?

I'll open a GH issue in our repository, and if everything is OK after our testing, we'll add this to the next plugin update (should be around early/mid April -> but no promises on the actual date :) ).

**Comment by martinkrcho** [comment]
Thanks, @capuderg . For now we are going to stop hiding notices on WP Mail SMTP's admin pages.

**Comment by alexander-sakal** [comment]
Hi @martinkrcho,

I'm the developer for WP Mail SMTP plugin.

We have implemented your first suggestion about clearing `network_admin_notices` hook.
We plan to release our 3.4 version with this implementation the next week.

It would be great if you can remove [this fix](https://github.com/wpwhitesecurity/admin-notices-manager/blob/master/includes/functions/core.php#L61) in your upcoming release.

**Comment by robert81** [comment]
Thank you @alexander-sakal 

We will indeed take care of this in the next release.

**Comment by jwjsystem** [comment]
@DannyWPWS @robert81 Performed basic checks for this one and can confirm it's solved in the latest build.
